version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
      tags:
        only: /^\d+\.\d+$/
    working_directory: /src
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push image to Docker Hub
          command: |
            REPO=$(basename $(git rev-parse --show-toplevel))
            TAG=$(git tag -l --points-at HEAD)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag app "$DOCKER_USER/${REPO}:${TAG}"
            docker push "$DOCKER_USER/${REPO}:${TAG}"